import * as fs from 'fs';
import { Report, Issue, Severity } from '../types';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
  info: '⚪',
};

const SEVERITY_ORDER: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function escapeMarkdown(text: string): string {
  return text.replace(/([\\`*_{}[\]()#+\-.!|])/g, '\\$1');
}

function renderIssue(issue: Issue, index: number): string {
  const lines: string[] = [];
  const emoji = SEVERITY_EMOJI[issue.severity];

  lines.push(`#### ${index + 1}. ${emoji} ${escapeMarkdown(issue.title)}`);
  lines.push('');
  lines.push(`- **Severity:** ${issue.severity.toUpperCase()}`);
  lines.push(`- **Scanner:** ${issue.scanner}`);
  lines.push(`- **ID:** \`${issue.id}\``);

  if (issue.file) {
    const location = issue.line ? `${issue.file}:${issue.line}` : issue.file;
    lines.push(`- **Location:** \`${location}\``);
  }

  lines.push('');
  lines.push('**Description:**');
  lines.push('');
  lines.push(issue.description);

  if (issue.fix) {
    lines.push('');
    lines.push('**Recommended Fix:**');
    lines.push('');
    lines.push(issue.fix);
  }

  if (issue.references && issue.references.length > 0) {
    lines.push('');
    lines.push('**References:**');
    lines.push('');
    for (const ref of issue.references) {
      lines.push(`- ${ref}`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

export function renderMarkdownReport(report: Report, outputPath?: string): string {
  const lines: string[] = [];

  // Header
  lines.push('# Web Secure Verification — Security Scan Report');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|----------|-------|');
  lines.push(`| **Project** | ${report.projectName} |`);
  lines.push(`| **Path** | \`${report.projectPath}\` |`);
  lines.push(`| **Scanned At** | ${new Date(report.scannedAt).toLocaleString()} |`);
  lines.push(`| **Duration** | ${formatDuration(report.duration)} |`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  lines.push(`| 🔴 Critical | ${report.summary.critical} |`);
  lines.push(`| 🟠 High | ${report.summary.high} |`);
  lines.push(`| 🟡 Medium | ${report.summary.medium} |`);
  lines.push(`| 🔵 Low | ${report.summary.low} |`);
  lines.push(`| ⚪ Info | ${report.summary.info} |`);
  lines.push(`| **Total** | **${report.summary.total}** |`);
  lines.push('');

  // Verdict
  const { summary } = report;
  if (summary.critical > 0 || summary.high > 0) {
    lines.push('> ❌ **SCAN FAILED** — Critical or high severity issues found that must be addressed.');
  } else if (summary.medium > 0 || summary.low > 0) {
    lines.push('> ⚠️ **SCAN PASSED WITH WARNINGS** — Medium or low severity issues found that should be reviewed.');
  } else {
    lines.push('> ✅ **SCAN PASSED** — No critical issues found.');
  }
  lines.push('');

  // Scanner overview
  lines.push('## Scanner Results');
  lines.push('');
  lines.push('| Scanner | Issues | Duration | Status |');
  lines.push('|---------|--------|----------|--------|');

  for (const result of report.results) {
    const status = result.error ? '⚠️ Error' : result.issues.length === 0 ? '✅ Clean' : `❌ ${result.issues.length} issues`;
    lines.push(`| ${result.scanner} | ${result.issues.length} | ${formatDuration(result.duration)} | ${status} |`);
  }
  lines.push('');

  // Issues by severity
  const allIssues: Issue[] = report.results.flatMap((r) => r.issues);

  if (allIssues.length === 0) {
    lines.push('## Issues');
    lines.push('');
    lines.push('No security issues were found.');
    lines.push('');
  } else {
    for (const severity of SEVERITY_ORDER) {
      const sevIssues = allIssues.filter((i) => i.severity === severity);
      if (sevIssues.length === 0) continue;

      const emoji = SEVERITY_EMOJI[severity];
      lines.push(`## ${emoji} ${severity.charAt(0).toUpperCase() + severity.slice(1)} Issues (${sevIssues.length})`);
      lines.push('');

      sevIssues.forEach((issue, idx) => {
        lines.push(renderIssue(issue, idx));
      });
    }
  }

  // Scanner errors
  const errors = report.results.filter((r) => r.error);
  if (errors.length > 0) {
    lines.push('## Scanner Errors');
    lines.push('');
    for (const result of errors) {
      lines.push(`- **${result.scanner}**: ${result.error}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by [web-secure-verification](https://www.npmjs.com/package/web-secure-verification) on ${new Date(report.scannedAt).toISOString()}*`);

  const markdown = lines.join('\n');

  if (outputPath) {
    fs.writeFileSync(outputPath, markdown, 'utf8');
  }

  return markdown;
}
